<?php
/**
 * Plugin Name:                   ShoppingFeed Yoast Metas
 * Plugin URI:                    https://wordpress.org/plugins/shoppingfeed/
 * Description:                   Add yoast metas to the feed generated by ShoppingFeed plugin
 * Author:                        Shopping-Feed
 * Author URI:                    https://www.shopping-feed.com/
 * Text Domain:                   shopping-feed-yoast-metas
 * Domain Path:                   /languages
 * Version:                       1.0.0
 * Requires at least WP:          5.2
 * Requires at least WooCommerce: 3.8 (3.9/4.0)
 * Requires PHP:                  7.2
 * License:                       GPLv3 or later
 * License URI:                   https://www.gnu.org/licenses/gpl-3.0.html
 */

namespace ShoppingFeed\ShoppingFeedWCYoastMetas;

// Exit on direct access
defined( 'ABSPATH' ) || exit;

function init() {
	if ( ! defined( 'SF_VERSION' ) || ! defined( 'WPSEO_VERSION' ) ) {
		add_action(
			'admin_notices',
			function () {
				?>
				<div id="message" class="notice notice-error">
					<p><?php esc_html_e( 'ShoppingFeed and Yoast SEO plugins must be activated', 'shopping-feed-yoast-metas' ); ?></p>
				</div>
				<?php
			}
		);

		return;
	}

	add_filter(
		'shopping_feed_extra_fields',
		function ( $fields, $product ) {
			/** @var \WC_Product $product */
			$fields[] = [
				'name'  => 'meta-title',
				'value' => ( new \WPSEO_Replace_Vars() )->replace( \WPSEO_Meta::get_value( 'title', $product->get_id() ), $product ),
			];
			$fields[] = [
				'name'  => 'meta-description',
				'value' => ( new \WPSEO_Replace_Vars() )->replace( \WPSEO_Meta::get_value( 'metadesc', $product->get_id() ), $product ),
			];

			return $fields;
		},
		10,
		2
	);
}

\add_action( 'plugins_loaded', __NAMESPACE__ . '\\init' );
